apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nebula-studio.fullname" . }}-nginx-config
data:
  nginx.conf: |
    server {
      listen        7000;
      server_name   127.0.0.1;

      location / {
        proxy_pass        http://127.0.0.1:7001;
        proxy_redirect    off;
        proxy_set_header  Host  $host;
        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Host $server_name;
        client_max_body_size 1024M;
      }

      location /upload-dir/ {
        root /;
        autoindex on;
      }

      location ~ ^/api-nebula/([A-Za-z0-9\/]+) {
        proxy_pass http://127.0.0.1:8080/api/$1;
      }
    }
