apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nebula-studio.name" . }}-config
data:
  studio-api.yaml: |
    Name: studio-api
    Host: 0.0.0.0
    Port: 7001
    MaxBytes: 1073741824
    Timeout: 60000
    Log:
      Mode: file
      Level: error
      KeepDays: 7
    Debug:
      Enable: false
    Auth:
      TokenName: "studio_token"
      AccessSecret: "login_secret"
      AccessExpire: 259200
    File:
      UploadDir: "/data/upload/"
      TasksDir: "/data/tasks"
    DB:
      # 1,2,3,4 corresponding to Silent, ERROR, Warn, INFO
      LogLevel: 4
      IgnoreRecordNotFoundError: false
      # AutoMigrate run auto migration for given models
      AutoMigrate: true
      # The database backend, either "mysql", "sqlite3".
      Type: "mysql"
      # Database host
      Host: "192.168.8.44:3306"
      # Database name
      Name: "hetao_test"
      # Database user
      User: "root"
      # Database password
      Password: "nebula"
      # For "sqlite3" only, database file path
      SqliteDbFilePath: "./data/tasks.db"
      # The maximum open connections of the pool.
      MaxOpenConns: 30
      # The maximum idle connections of the pool.
      MaxIdleConns: 10