apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nebula-studio.fullname" . }}
  labels:
    {{- include "nebula-studio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nebula-studio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nebula-studio.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: http-gateway
          image: "{{ .Values.image.httpGateway.name }}:{{ .Values.image.httpGateway.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: USER
              value: root
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            {{- toYaml .Values.resources.httpGateway | nindent 12 }}
          volumeMounts:
            - name: upload-data
              mountPath: /upload
        - name: nebula-studio
          image: "{{ .Values.image.nebulaStudio.name }}:{{ .Values.image.nebulaStudio.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: UPLOAD_DIR
              value: /upload
          ports:
            - containerPort: 7001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 7001
          readinessProbe:
            httpGet:
              path: /
              port: 7001
          # Patch due to https://github.com/vesoft-inc/nebula-studio/issues/22
          command:
            - sh
            - -c
            - |
              sed 's/\(.*docker-start.*studio\)",/\1 --workers=3",/' -i package.json
              npm run docker-start
          resources:
            {{- toYaml .Values.resources.nebulaStudio | nindent 12 }}
          volumeMounts:
            - name: upload-data
              mountPath: /upload
        - name: nginx
          image: "{{ .Values.image.nginx.name }}:{{ .Values.image.nginx.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 7000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 7000
          readinessProbe:
            httpGet:
              path: /
              port: 7000
          resources:
            {{- toYaml .Values.resources.nginx | nindent 12 }}
          volumeMounts:
            - name: upload-data
              mountPath: /upload
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/nebula.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "nebula-studio.fullname" . }}-nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: upload-data
          persistentVolumeClaim:
            claimName: {{ include "nebula-studio.fullname" . }}-upload-data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
