version: '3.4'
services:
  web:
    image: vesoft/nebula-graph-studio:v3.8.0-beta
    environment:
      USER: root
    ports:
      - 7001:7001
    networks:
      - nebula-web

networks:
  nebula-web: