replicaCount: 1

image:
  pullPolicy: IfNotPresent
  httpGateway:
    name: vesoft/nebula-http-gateway
    version: v2.1.0
  nebulaImporter:
    name: vesoft/nebula-importer
    version: v2
  nebulaStudio:
    name: vesoft/nebula-graph-studio
    version: v3
  nginx:
    name: nginx
    version: alpine

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 7001

resources:
  httpGateway:
  nebulaImporter:
  nebulaStudio:
  nginx:

persistent:
  storageClassName: ""
  size: 5Gi

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
