name: Studio Release
on:
  release:
    types:
      - published
jobs:
  tar-package:
    name: build tar package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - centos7
    container:
      image: vesoft/nebula-dev:${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: source/nebula-graph-studio
      - uses: actions/checkout@v2
        with:
          repository: vesoft-inc/nebula-http-gateway
          path: source/nebula-http-gateway
          ref: v2.1.1
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: Package
        run: bash ./source/nebula-graph-studio/scripts/tar/pack.sh
      - name: Upload to OSS
        run: bash ./source/nebula-graph-studio/scripts/tar/upload.sh ${{ secrets.OSS_ENDPOINT }} ${{ secrets.OSS_ID }} ${{ secrets.OSS_SECRET }} ${{ secrets.OSS_URL }}
  rpm-package:
    name: build rpm package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - centos7
    container:
      image: vesoft/nebula-dev:${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: source/nebula-graph-studio
      - uses: actions/checkout@v2
        with:
          repository: vesoft-inc/nebula-http-gateway
          path: source/nebula-http-gateway
          ref: v2.1.1
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: Package
        run: bash ./source/nebula-graph-studio/scripts/rpm/pack.sh
      - name: Upload oss
        run: bash ./source/nebula-graph-studio/scripts/rpm/upload.sh ${{ secrets.OSS_ENDPOINT }} ${{ secrets.OSS_ID }} ${{ secrets.OSS_SECRET }} ${{ secrets.OSS_URL }}
  docker-image:
    name: docker image build
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout Github Action
      uses: actions/checkout@master
    - 
      name: set track
      run: bash ./scripts/setEventTracking.sh ${{ secrets.GA_ID }}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Build
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: vesoft/nebula-graph-studio:v3.1.0